# Generated by Django 3.2.13 on 2023-02-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAdministrationDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_reserch_img', models.ImageField(upload_to='academicAdministraction/faculty')),
                ('director_reserch_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AntiRaggingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Anti Ragging Committee',
            },
        ),
        migrations.CreateModel(
            name='GoverningBodyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Governing Body',
            },
        ),
        migrations.CreateModel(
            name='GoverningBodyOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='GoverningBodyOrderFile')),
            ],
            options={
                'verbose_name': 'GoverningBodyOrderFile',
                'verbose_name_plural': 'GoverningBodyOrderFiles',
            },
        ),
        migrations.CreateModel(
            name='GrivenceCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IQACExecutiveCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'IQAC Executive Commitee',
            },
        ),
        migrations.CreateModel(
            name='IQACFormationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.FileField(upload_to='IQACFormationNotice')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'IQAC Formation Notice',
            },
        ),
        migrations.CreateModel(
            name='MandatoryDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='MandatoryDisclosure')),
            ],
            options={
                'verbose_name_plural': 'Mandatory Disclosure',
            },
        ),
        migrations.CreateModel(
            name='ProfileHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qulaification', models.CharField(max_length=500)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('exedir', 'Executive Director')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PTAExecutiveCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'PTA Executive Commitee',
            },
        ),
        migrations.CreateModel(
            name='PTAMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tudent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'PTA  Members',
            },
        ),
        migrations.CreateModel(
            name='SCSTMonitoringCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Sc/St Monitoing  Committee',
            },
        ),
        migrations.CreateModel(
            name='ExaminationCellFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default=None, max_length=200)),
                ('faculty', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAdministractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('faculty', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
            ],
        ),
    ]
