# Generated by Django 3.2.17 on 2023-04-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Approvals')),
            ],
        ),
        migrations.CreateModel(
            name='KtuAicteRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='KtuAicteRegulations')),
            ],
            options={
                'verbose_name_plural': 'KTU/AICTE Regulations',
            },
        ),
    ]
