# Generated by Django 3.2.13 on 2022-12-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governingbody',
            options={'verbose_name_plural': 'Governing Body'},
        ),
    ]
