# Generated by Django 3.2.13 on 2022-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_alter_governingbody_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQACExecutiveCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'IQAC Executive Commitee',
            },
        ),
        migrations.CreateModel(
            name='IQACFormationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.FileField(upload_to='IQACFormationNotice')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'IQAC Formation Notice',
            },
        ),
    ]
