# Generated by Django 3.2.17 on 2023-05-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_approvals_ktuaicteregulations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approvals',
        ),
        migrations.DeleteModel(
            name='KtuAicteRegulations',
        ),
        migrations.DeleteModel(
            name='MandatoryDisclosure',
        ),
    ]
