# Generated by Django 3.2.13 on 2022-12-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_iqacexecutivecommitee_iqacformationnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningBodyOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='GoverningBodyOrderFile')),
            ],
            options={
                'verbose_name': 'GoverningBodyOrderFile',
                'verbose_name_plural': 'GoverningBodyOrderFiles',
            },
        ),
        migrations.RenameModel(
            old_name='GoverningBody',
            new_name='GoverningBodyMembers',
        ),
    ]
