# Generated by Django 3.2.13 on 2022-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_auto_20221209_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTAExecutiveCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'PTA Executive Commitee',
            },
        ),
    ]
