# Generated by Django 3.2.17 on 2023-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20230818_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQACMeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='IQACMeetingMinutes')),
            ],
        ),
    ]
