# Generated by Django 3.2.17 on 2023-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_iqacmeetingminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqacmeetingminutes',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='2020-21', max_length=10),
        ),
    ]
