# Generated by Django 3.2.13 on 2022-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_ptaexecutivecommitee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTAMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tudent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'PTA  Members',
            },
        ),
    ]
