# Generated by Django 3.2.17 on 2023-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_iqacmeetingminutes_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
