# Generated by Django 3.2.13 on 2022-12-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_ptamembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qulaification', models.CharField(max_length=500)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('exedir', 'Executive Director')], max_length=100)),
            ],
        ),
    ]
