# Generated by Django 3.2.13 on 2022-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_antiraggingcommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCSTMonitoringCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Sc/St Monitoing  Committee',
            },
        ),
    ]
