# Generated by Django 3.2.17 on 2023-11-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20230929_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievancebody',
            name='classs',
        ),
        migrations.AddField(
            model_name='grievancebody',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Grievances'), ('administrative', 'Administrative Grievances'), ('faculty_staff', 'Faculty and Staff-related Issues'), ('infrastructure_facilities', 'Infrastructure and Facilities'), ('health_safety', 'Health and Safety'), ('financial', 'Financial Matters'), ('discipline', 'Code of Conduct and Discipline'), ('research', 'Research and Project-related Grievances'), ('harrasement', 'Harassment and Discrimination'), ('interpersonal', 'Interpersonal and Social Concerns'), ('other', 'Other Grievances')], default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='grivenceuser',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('parents', 'Parents'), ('other', 'Other')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='grievancebody',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('parents', 'Parents'), ('other', 'Other')], default=0, max_length=30),
        ),
    ]
