# Generated by Django 3.2.13 on 2022-12-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_achivements_date'),
        ('Administration', '0009_scstmonitoringcommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationCellFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculties', models.ManyToManyField(to='website.Faculty')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
