# Generated by Django 3.2.17 on 2023-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20231101_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievancebody',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('parents', 'Parents'), ('other', 'Other')], default='student', max_length=30),
        ),
        migrations.AlterField(
            model_name='grivenceuser',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('parents', 'Parents'), ('other', 'Other')], default='student', max_length=30),
        ),
    ]
