# Generated by Django 3.2.13 on 2023-01-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0010_examinationcellfaculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationcellfaculty',
            options={'verbose_name': ' Examination Cell Faculty', 'verbose_name_plural': 'Examination Cell Faculty'},
        ),
    ]
