# Generated by Django 3.2.17 on 2023-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20231101_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievancebody',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Grievances'), ('exam', 'Exam Grievances'), ('administrative', 'Administrative Grievances'), ('faculty_staff', 'Faculty and Staff-related Issues'), ('infrastructure_facilities', 'Infrastructure and Facilities'), ('health_safety', 'Health and Safety'), ('financial', 'Financial Matters'), ('discipline', 'Code of Conduct and Discipline'), ('research', 'Research and Project-related Grievances'), ('harrasement', 'Harassment and Discrimination'), ('interpersonal', 'Interpersonal and Social Concerns'), ('scst', 'SC/ST Related Grievances'), ('other', 'Other Grievances')], default=0, max_length=30),
        ),
    ]
