# Generated by Django 3.2.13 on 2023-02-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_alter_examinationcellfaculty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='MandatoryDisclosure')),
            ],
            options={
                'verbose_name_plural': 'Mandatory Disclosure',
            },
        ),
    ]
