# Generated by Django 3.2.13 on 2023-02-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20230207_1331'),
        ('Administration', '0012_mandatorydisclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_reserch_img', models.ImageField(upload_to='academicAdministraction/faculty')),
                ('director_reserch_name', models.CharField(max_length=200)),
                ('faculties', models.ManyToManyField(to='website.Faculty')),
            ],
        ),
    ]
