# Generated by Django 3.2.13 on 2023-02-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20230207_1331'),
        ('Administration', '0014_auto_20230214_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAdministractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('faculty', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAdministrationDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_reserch_img', models.ImageField(upload_to='academicAdministraction/faculty')),
                ('director_reserch_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicAdministration',
        ),
    ]
