# Generated by Django 3.2.23 on 2023-11-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20231127_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'External Audits',
            },
        ),
        migrations.AlterModelOptions(
            name='internalaudit',
            options={'verbose_name_plural': 'Internal Audits'},
        ),
    ]
