# Generated by Django 3.2.23 on 2023-11-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20231130_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationCellRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ExamRulesAndRegulations')),
            ],
        ),
        migrations.AlterModelOptions(
            name='iqacexecutivecommitee',
            options={'verbose_name_plural': 'IQAC Executive Commitees'},
        ),
        migrations.AlterModelOptions(
            name='iqacformationnotice',
            options={'verbose_name_plural': 'IQAC Formation Notices'},
        ),
        migrations.AddField(
            model_name='iqacexecutivecommitee',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
