# Generated by Django 3.2.25 on 2025-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_auto_20250219_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaudit',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('DS', 'DS'), ('BSH', 'BSH'), ('None', 'None')], max_length=200),
        ),
    ]
