# Generated by Django 3.2.25 on 2025-06-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_alter_internalaudit_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicadministrationdirector',
            name='director_reserch_role',
            field=models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('aca_dir', 'Academic Director'), ('res_dir', 'Research Director'), ('out_dir', 'OutReach Director')], default='principal', max_length=200),
        ),
    ]
