<<<<<<< HEAD
=======
# Generated by Django 3.2.25 on 2025-07-18 17:27
>>>>>>> ca0068e (grievance model updated)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_academicadministrationdirector_director_reserch_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceUserCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='grievance_users_csv/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
