# Generated by Django 3.2.25 on 2026-01-22 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_auto_20260121_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='MeetingMinutes')),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('icc', 'Internal Complaints Committee (ICC)'), ('grievance', 'Student Grievance & Redressal'), ('anti_ragging', 'Anti-Ragging Committee'), ('eoc', 'Equal Opportunity Cell'), ('sedg', 'SEDG Cell'), ('accessibility', 'Accessibility Committee'), ('sc_st', 'SC/ST Committee'), ('minority', 'Minority Cell'), ('obc', 'OBC Cell'), ('idp', 'Institutional Development Plan'), ('other', 'Other')], default='other', max_length=100)),
            ],
            options={
                'verbose_name': 'Meeting Minute / UGC Document',
                'verbose_name_plural': 'Meeting Minutes & UGC Documents',
            },
        ),
    ]
