# Generated by Django 3.2.25 on 2026-01-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_meetingminutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='category',
            field=models.CharField(choices=[('icc', 'Internal Complaints Committee (ICC)'), ('grievance', 'Student Grievance & Redressal'), ('anti_ragging', 'Anti-Ragging Committee'), ('eoc', 'Equal Opportunity Cell'), ('sedg', 'SEDG Cell'), ('accessibility', 'Accessibility Committee'), ('sc_st', 'SC/ST Committee'), ('minority', 'Minority Cell'), ('obc', 'OBC Cell'), ('idp', 'Institutional Development Plan'), ('rnd', 'Research & Development'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
