# Generated by Django 3.2.25 on 2026-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritAdmissionBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('account_no', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Merit Admission Bank Detail',
                'verbose_name_plural': 'Merit Admission Bank Details',
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Admission Queries'), ('form', 'Data Entry Form Queries')], default='general', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Merit Admission Contact',
                'verbose_name_plural': 'Merit Admission Contacts',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('original', 'Original'), ('copy', 'Copy')], default='original', max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Merit Admission Required Document',
                'verbose_name_plural': 'Merit Admission Required Documents',
                'ordering': ['type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionDocumentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Merit Admission Document Note',
                'verbose_name_plural': 'Merit Admission Document Notes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_1', models.TextField(blank=True)),
                ('warning_2', models.TextField(blank=True)),
                ('form_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Merit Admission Form Link',
                'verbose_name_plural': 'Merit Admission Form Links',
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(help_text='e.g. July 21st', max_length=100)),
                ('departments', models.CharField(help_text='e.g. CS-DS, CS-BS, EEE', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Merit Admission Schedule Slot',
                'verbose_name_plural': 'Merit Admission Schedule Slots',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Merit Admission Tutorial',
                'verbose_name_plural': 'Merit Admission Tutorials',
            },
        ),
        migrations.CreateModel(
            name='MeritAdmissionUniformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boys_fee', models.CharField(help_text='e.g. ₹11,000', max_length=50)),
                ('girls_fee', models.CharField(help_text='e.g. ₹12,000', max_length=50)),
                ('note', models.CharField(blank=True, default='*Cash only*', max_length=300)),
            ],
            options={
                'verbose_name': 'Merit Admission Uniform Fee',
                'verbose_name_plural': 'Merit Admission Uniform Fees',
            },
        ),
    ]
