# Generated by Django 3.2.25 on 2026-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_seed_merit_admission_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governingbodymembers',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Governing Body'},
        ),
        migrations.AddField(
            model_name='governingbodymembers',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
