from django.contrib import admin

from departments.models import *

# Register your models here.
admin.site.register(DepHero)
admin.site.register(POES)
admin.site.register(POS)
admin.site.register(PSOS)
admin.site.register(Vission)
admin.site.register(Mission)
admin.site.register(DepUpdates)
admin.site.register(ProfessionalBodies)
admin.site.register(ProfessionalBodiesTeamMembers)
admin.site.register(ProfessionalBodiesEvents)
admin.site.register(SyllabusPDFS)
admin.site.register(Handouts)
admin.site.register(Laboratories)
admin.site.register(Achivements)
admin.site.register(Events)
admin.site.register(Contact)
admin.site.register(DepAbout)
admin.site.register(NewsLetters)
admin.site.register(Associations)
admin.site.register(AssociationsEvents)
admin.site.register(AssociationTeamMembers)
admin.site.register(Objectives)
admin.site.register(InnovativeTLM)
admin.site.register(TLM_table)
admin.site.register(DAB)
admin.site.register(DabTable)
admin.site.register(PAC)
admin.site.register(PacTable)
admin.site.register(Streams)
admin.site.register(StreamComm)
admin.site.register(Students)
admin.site.register(AchievementTables)
admin.site.register(Econtent)
admin.site.register(Products)
admin.site.register(Mooc_courses)
admin.site.register(Fdps)
admin.site.register(Social_activities)
admin.site.register(Holistics)
admin.site.register(Higher)
admin.site.register(Placements)
admin.site.register(Activity)
admin.site.register(Alumni)
