version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Mounts your local code into the container for live-reloading
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: