services:
  db:
    image: postgres:14-alpine
    platform: linux/arm64
    volumes:
      - production_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    entrypoint: /app/entrypoint.prod.sh
    restart: always
    expose:
      - 8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN}
      - DEBUG=0
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
  
  proxy:
    build:
      context: ./docker/proxy
    platform: linux/arm64
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
  
  certbot:
    platform: linux/arm64
    build:
      context: ./docker/certbot
    command: echo "Skipping certbot for now..."  # Uncomment this line to skip certbot
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy

volumes:
  production_postgres_data:
  certbot-web:
  proxy-dhparams:
  certbot-certs: