# Generated by Django 4.0.4 on 2022-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=10)),
            ],
        ),
    ]
