# Generated by Django 3.2.13 on 2023-02-16 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('name_of_client', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('amount_recived', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPartnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('name_of_client', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achivements')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Achivement',
                'verbose_name_plural': 'Achivements',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum', models.FileField(upload_to='AlumniMemorandum')),
                ('by_laws', models.FileField(upload_to='AlumniByLaws')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('investor', models.CharField(default='', max_length=500, verbose_name='Name of Investor')),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Facilities')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='star', max_length=100)),
                ('link_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='faculty@cce.edu.in', max_length=254)),
                ('image', models.ImageField(default='faculty.jpeg', upload_to='faculty')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None'), ('administrative_staff', 'Administrative Staff'), ('wardens', 'Wardens '), ('supporting_staff', 'Supporting Staff'), ('security_staff', 'Security Staff')], default='None', max_length=200)),
                ('profile', models.FileField(default='faculty_profile.pdf', upload_to='faculty_profile')),
                ('priorities', models.IntegerField(default=10)),
                ('doj', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyStudentPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=300, verbose_name='Name Of Author')),
                ('dep', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100, verbose_name='Department of Faculty/student')),
                ('journal', models.CharField(max_length=500, verbose_name='Name Of Journal')),
                ('year', models.CharField(max_length=50, verbose_name='Year Of Publication')),
                ('details', models.FileField(upload_to='research/publications', verbose_name='Details of Publictaion')),
            ],
        ),
        migrations.CreateModel(
            name='FundedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('principal_investigator', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('funding_agency', models.CharField(max_length=100)),
                ('grand_sanctioned', models.IntegerField()),
                ('grand_recived', models.IntegerField()),
                ('publictaion_details', models.FileField(upload_to='research/FundedProjects')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryEventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hero_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Heros_Images')),
                ('video', models.FileField(blank=True, upload_to='Heros_Videos')),
                ('type', models.CharField(choices=[('img', 'IMAGE'), ('vdo', 'VIDEO')], default='img', max_length=200)),
                ('page', models.CharField(choices=[('management', 'Management'), ('directors_desk', 'Directors Desk'), ('facilities', 'Facilities'), ('principals_desk', "Principal's Desk"), ('cce_in_media', 'CCE In Media'), ('governing_body', 'Governing Body'), ('organogram', 'Organogram'), ('mandatory_disclosure', 'Mandatory Disclosure'), ('antiraging_cell', 'AntiRaging Cell'), ('grivence_redressal_sysytem', 'Grivence Redressal System'), ('sc_st_monitoring_commite', 'Sc/St Monitoring Commitee'), ('iqac', 'IQAC'), ('examination_cell', 'Examination Cell'), ('pta', 'PTA'), ('office', 'office'), ('nss', 'NSS'), ('college_union', 'College Union'), ('facilities', 'Facilities'), ('pta', 'PTA'), ('None', 'None'), ('research', 'Research'), ('arts', 'Arts'), ('sports', 'Sports'), ('placements', 'Placements'), ('admissions', 'Admissions'), ('academic_research', 'Academic Research'), ('womencell', 'Women Cell'), ('clubs', 'Clubs'), ('iic', 'IIC')], default='None', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hero Images',
            },
        ),
        migrations.CreateModel(
            name='HomeAnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='HomeAnouncements/announcement.png', upload_to='HomeAnouncements', verbose_name='image')),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('link_name', models.CharField(default='', max_length=100)),
                ('link', models.URLField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='HomeEvents/1.jpg', upload_to='HomeEvents')),
                ('img2', models.ImageField(default='HomeEvents/2.jpg', upload_to='HomeEvents')),
                ('img3', models.ImageField(default='HomeEvents/3.jpg', upload_to='HomeEvents')),
                ('img4', models.ImageField(default='HomeEvents/2.jpg', upload_to='HomeEvents')),
                ('heading', models.CharField(max_length=30)),
                ('sub_heading', models.CharField(max_length=50)),
                ('sub_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Recruiters')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('quote', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='UpcomingEvents/1.jpg', upload_to='UpcomingEvents')),
                ('title', models.CharField(max_length=80)),
                ('sub_title', models.TextField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery')),
                ('video', models.FileField(blank=True, upload_to='Heros_Videos')),
                ('type', models.CharField(choices=[('img', 'IMAGE'), ('vdo', 'VIDEO')], default='img', max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'ME'), ('CIVIL', 'CE'), ('BSH', 'BSH'), ('All', 'All')], default='None', max_length=200)),
                ('event_type', models.ManyToManyField(default='None', to='website.GalleryEventTypes')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.ManyToManyField(to='website.Role'),
        ),
    ]
