# Generated by Django 4.0.4 on 2022-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homeevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeevents',
            name='sub_text',
            field=models.CharField(max_length=500),
        ),
    ]
