# Generated by Django 4.0.4 on 2022-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_homeevents_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeevents',
            name='sub_text',
            field=models.TextField(),
        ),
    ]
