# Generated by Django 4.0.4 on 2022-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_testimonials_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='testimonials'),
        ),
    ]
