# Generated by Django 3.2.17 on 2023-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_admissionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(upload_to='admission/')),
            ],
        ),
    ]
