# Generated by Django 4.0.4 on 2022-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='quote',
            field=models.CharField(max_length=200),
        ),
    ]
