# Generated by Django 4.0.4 on 2022-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_testimonials_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeevents',
            name='img1',
            field=models.ImageField(default='HomeEvents/1.jpg', upload_to='HomeEvents'),
        ),
        migrations.AddField(
            model_name='homeevents',
            name='img2',
            field=models.ImageField(default='HomeEvents/2.jpg', upload_to='HomeEvents'),
        ),
        migrations.AddField(
            model_name='homeevents',
            name='img3',
            field=models.ImageField(default='HomeEvents/3.jpg', upload_to='HomeEvents'),
        ),
        migrations.AddField(
            model_name='homeevents',
            name='img4',
            field=models.ImageField(default='HomeEvents/2.jpg', upload_to='HomeEvents'),
        ),
    ]
