# Generated by Django 3.2.17 on 2023-11-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20230929_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='year',
            field=models.CharField(default=2023, max_length=20),
            preserve_default=False,
        ),
    ]
