# Generated by Django 4.1.1 on 2022-09-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_homeevents_img1_homeevents_img2_homeevents_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='upcomingEvents')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
    ]
