# Generated by Django 3.2.17 on 2023-11-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_conference_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='sub_title',
            field=models.TextField(),
        ),
    ]
