# Generated by Django 4.0.4 on 2022-10-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_upcomingevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
    ]
