# Generated by Django 3.2.17 on 2023-11-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_upcomingevents_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nptel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_year', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='nptel')),
            ],
        ),
    ]
