# Generated by Django 4.1.1 on 2022-10-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_role_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='doj',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='faculty.jpeg', upload_to='faculty'),
        ),
    ]
