# Generated by Django 4.0.4 on 2022-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_faculty_department_alter_faculty_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='faculty@cce.edu.in', max_length=254),
        ),
    ]
