# Generated by Django 4.0.4 on 2022-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_faculty_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image_2',
            field=models.ImageField(default='faculty.jpeg', upload_to='faculty'),
        ),
    ]
