# Generated by Django 4.0.4 on 2022-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_faculty_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='priorities',
            field=models.IntegerField(default=0),
        ),
    ]
