# Generated by Django 4.0.4 on 2022-10-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_faculty_priorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='priorities',
            field=models.IntegerField(default=10),
        ),
    ]
