# Generated by Django 4.0.4 on 2022-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_faculty_priorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('BSH', 'BSH'), ('All', 'All')], default='None', max_length=200),
        ),
    ]
