# Generated by Django 3.2.13 on 2022-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_cceinmedia_ccemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum', models.FileField(upload_to='AlumniMemorandum')),
                ('by_laws', models.FileField(upload_to='AlumniByLaws')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Facilities')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='UpcomingEvents/1.jpg', upload_to='UpcomingEvents')),
                ('title', models.CharField(max_length=80)),
                ('sub_title', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CCEinMedia',
        ),
        migrations.DeleteModel(
            name='CCEManagement',
        ),
    ]
