# Generated by Django 4.0.4 on 2022-11-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_cceinmedia_ccemanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
