# Generated by Django 3.2.13 on 2022-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20221114_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Recruiters')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
