# Generated by Django 3.2.17 on 2023-12-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_hero_image_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHD_Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('institute', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('researchArea', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pursuing', 'Pursuing'), ('awarded', 'Awarded')], default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'PHD_Faulty',
                'verbose_name_plural': 'PHD_Faultys',
            },
        ),
        migrations.CreateModel(
            name='ResearchScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('guideName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ResearchScholar',
                'verbose_name_plural': 'ResearchScholars',
            },
        ),
    ]
