# Generated by Django 3.2.17 on 2023-12-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_phd_faculty_researchscholar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardedPHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('researchArea', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'AwardedPHD',
                'verbose_name_plural': 'AwardedPHDs',
            },
        ),
        migrations.RemoveField(
            model_name='phd_faculty',
            name='department',
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='researchArea',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
