# Generated by Django 3.2.13 on 2022-11-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_recruiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='image_2',
        ),
    ]
