# Generated by Django 3.2.13 on 2022-11-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alumni_alumnicommittee_governingbody_upcomingevents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governingbody',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='governingbody',
            name='title',
        ),
    ]
