# Generated by Django 3.2.13 on 2022-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alumni_alumnicommittee_governingbody_upcomingevents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Facilities')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='governingbody',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='governingbody',
            name='title',
        ),
    ]
