# Generated by Django 3.2.13 on 2022-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_faculty_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Heros_Images')),
            ],
        ),
    ]
