# Generated by Django 3.2.13 on 2022-11-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20221112_0623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoverningBody',
        ),
    ]
