# Generated by Django 3.2.13 on 2022-11-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20221114_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governingbody',
            name='title',
        ),
    ]
