# Generated by Django 3.2.13 on 2022-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_image',
            name='page',
            field=models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Facilities', 'Facilities'), ('Gallery', 'Gallery'), ('Alumni', 'Alumni'), ('Contact', 'Contact')], default='None', max_length=200),
        ),
    ]
