# Generated by Django 3.2.13 on 2022-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_delete_governingbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='date',
            field=models.DateField(),
        ),
    ]
