# Generated by Django 3.2.23 on 2023-12-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_phd_faculty_dept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phd_faculty',
            options={'verbose_name': 'PHD Faculty', 'verbose_name_plural': 'PHD Facultys'},
        ),
        migrations.AlterModelOptions(
            name='researchscholar',
            options={'verbose_name': 'Research Scholar', 'verbose_name_plural': 'Research Scholars'},
        ),
    ]
