# Generated by Django 3.2.13 on 2022-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_iqacexecutivecommitee_iqacformationnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_image',
            name='type',
            field=models.CharField(choices=[('img', 'IMAGE'), ('vdo', 'VIDEO')], default='img', max_length=200),
        ),
        migrations.AddField(
            model_name='hero_image',
            name='video',
            field=models.FileField(blank=True, upload_to='Heros_Videos'),
        ),
        migrations.AlterField(
            model_name='hero_image',
            name='image',
            field=models.ImageField(blank=True, upload_to='Heros_Images'),
        ),
    ]
