# Generated by Django 3.2.25 on 2025-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20250219_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('student_mobile', models.CharField(max_length=15)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Kerala State Board', 'Kerala State Board'), ('Other', 'Other')], max_length=50)),
                ('physics_mark', models.IntegerField()),
                ('chemistry_mark', models.IntegerField()),
                ('mathematics_mark', models.IntegerField()),
                ('pcm_percentage', models.FloatField()),
                ('higher_secondary_percentage', models.FloatField()),
                ('preference_1', models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science & Engineering (Data Science)', 'Computer Science & Engineering (Data Science)')], max_length=100)),
                ('preference_2', models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science & Engineering (Data Science)', 'Computer Science & Engineering (Data Science)')], max_length=100)),
                ('preference_3', models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science & Engineering (Data Science)', 'Computer Science & Engineering (Data Science)')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='admissiongraph',
            name='graph',
            field=models.ImageField(upload_to='admissionForm/'),
        ),
        migrations.AlterField(
            model_name='hero_image',
            name='page',
            field=models.CharField(choices=[('management', 'Management'), ('directors_desk', 'Directors Desk'), ('facilities', 'Facilities'), ('principals_desk', "Principal's Desk"), ('cce_in_media', 'CCE In Media'), ('governing_body', 'Governing Body'), ('organogram', 'Organogram'), ('mandatory_disclosure', 'Mandatory Disclosure'), ('antiraging_cell', 'AntiRaging Cell'), ('grivence_redressal_sysytem', 'Grivence Redressal System'), ('sc_st_monitoring_commite', 'Sc/St Monitoring Commitee'), ('iqac', 'IQAC'), ('examination_cell', 'Examination Cell'), ('pta', 'PTA'), ('office', 'office'), ('nss', 'NSS'), ('college_union', 'College Union'), ('facilities', 'Facilities'), ('pta', 'PTA'), ('None', 'None'), ('research', 'Research'), ('arts', 'Arts'), ('sports', 'Sports'), ('placements', 'Placements'), ('admissionForms', 'AdmissionForms'), ('academic_research', 'Academic Research'), ('womencell', 'Women Cell'), ('clubs', 'Clubs'), ('iic', 'IIC'), ('all_committees', 'All Committees'), ('programs_offered', 'Programs Offered'), ('hr_manual', 'HR Policy'), ('vision_2035', 'Vision 2035'), ('annual_report', 'Annual Report'), ('college_handbook', 'College Handbook'), ('academic_calendar', 'academic Calendar'), ('audited_statements', 'Audited Statements'), ('college_magazine', 'College Magazine'), ('ktu_aicte_regulations', 'KTU AICTE Regulations'), ('approvals', 'Approvals'), ('techies_park', 'Techies Park'), ('events', 'Events'), ('study_abroad', 'Study Abroad'), ('library', 'Library'), ('disciplinary_committee', 'Disciplinary Committee'), ('internal_audit_page', 'Internal Audit'), ('external_audit_page', 'External Audit'), ('ieee', 'IEEE'), ('quality_policy', 'Quality Policy'), ('mentoring', 'Mentoring'), ('ccil', 'CCIL'), ('international_relations', 'International Relations Cell'), ('webteam', 'webteam'), ('ccevr', 'ccevr'), ('result_analysis', 'Result Analysis'), ('campus_tour', 'Campus Tour')], default='None', max_length=200),
        ),
    ]
