# Generated by Django 3.2.13 on 2022-12-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20221209_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IQACExecutiveCommitee',
        ),
        migrations.DeleteModel(
            name='IQACFormationNotice',
        ),
    ]
