# Generated by Django 3.2.13 on 2022-12-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20221209_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero_image',
            options={'verbose_name_plural': 'Hero Images'},
        ),
    ]
