# Generated by Django 3.2.25 on 2025-08-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20250616_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAnnouncementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Link text')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.homeanouncement')),
            ],
            options={
                'verbose_name': 'Announcement Link',
                'verbose_name_plural': 'Announcement Links',
                'ordering': ['order'],
            },
        ),
    ]
