# Generated by Django 3.2.13 on 2022-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_hero_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='icon',
            field=models.CharField(default='star', max_length=100),
        ),
        migrations.AddField(
            model_name='facilities',
            name='link_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
