# Generated by Django 3.2.25 on 2025-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_homeannouncementlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeanouncement',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeanouncement',
            name='link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
