# Generated by Django 3.2.25 on 2025-08-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20250810_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeannouncementlink',
            options={'verbose_name': 'Announcement Link', 'verbose_name_plural': 'Announcement Links'},
        ),
        migrations.RemoveField(
            model_name='homeannouncementlink',
            name='open_in_new_tab',
        ),
        migrations.RemoveField(
            model_name='homeannouncementlink',
            name='order',
        ),
        migrations.AlterField(
            model_name='homeannouncementlink',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Link name'),
        ),
        migrations.AlterField(
            model_name='homeannouncementlink',
            name='url',
            field=models.URLField(max_length=300, verbose_name='Link'),
        ),
    ]
