# Generated by Django 3.2.25 on 2026-01-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20260121_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='aicte_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AICTE ID'),
        ),
    ]
