# Generated by Django 3.2.25 on 2026-01-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_faculty_aicte_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('BS', 'Computer Science (Business Systems)'), ('MBA', 'Master of Business Administration'), ('None', 'None'), ('administrative_staff', 'Administrative Staff'), ('wardens', 'Wardens '), ('supporting_staff', 'Supporting Staff'), ('security_staff', 'Security Staff')], default='None', max_length=200),
        ),
    ]
