# Generated by Django 3.2.13 on 2022-12-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20221222_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
