# Generated by Django 3.2.25 on 2026-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_hero_image_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAComplianceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display label shown on the NBA page, e.g. 'CSE SAR 2024'", max_length=300, verbose_name='Link Title')),
                ('url', models.URLField(help_text='Paste the full URL of the compliance document', max_length=500, verbose_name='Drive / Document URL')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('BSH', 'Basic Sciences and Humanities'), ('General', 'General / College-Wide')], default='General', max_length=50, verbose_name='Department')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within each department')),
            ],
            options={
                'verbose_name': 'NBA Compliance Link',
                'verbose_name_plural': 'NBA Compliance Links',
                'ordering': ['department', 'order', 'name'],
            },
        ),
    ]
