# Generated by Django 3.2.25 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_nba_compliance_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicconsultancy',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicpartnership',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionstatistics',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='awardedphd',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('BS', 'Computer Science (Business Systems)'), ('MBA', 'Master of Business Administration'), ('None', 'None'), ('administrative_staff', 'Administrative Staff'), ('wardens', 'Wardens '), ('supporting_staff', 'Supporting Staff'), ('security_staff', 'Security Staff')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultystudentpublications',
            name='dep',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100, verbose_name='Department of Faculty/student'),
        ),
        migrations.AlterField(
            model_name='fundedprojects',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='phd_faculty',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='researchscholar',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], max_length=100),
        ),
    ]
