# Generated by Django 3.2.13 on 2022-12-28 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20221228_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
