# Generated by Django 3.2.13 on 2023-01-03 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_hero_image_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('link_name', models.CharField(default='', max_length=100)),
                ('link', models.URLField(default='', max_length=100)),
            ],
        ),
    ]
