# Generated by Django 3.2.13 on 2023-01-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_homeanouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeanouncement',
            name='image',
            field=models.ImageField(default='HomeAnouncements/announcement.png', upload_to='HomeAnouncements', verbose_name='image'),
        ),
    ]
