# Generated by Django 3.2.13 on 2023-01-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_homeanouncement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='department',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='quote',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='role',
            field=models.CharField(max_length=150),
        ),
    ]
