# Generated by Django 3.2.13 on 2023-01-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20230104_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('name_of_client', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('work_status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('amount_recived', models.IntegerField()),
                ('publictaion_details', models.FileField(upload_to='research/AcademicConsultancy')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPartnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('name_of_client', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='FundedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('principal_investigator', models.CharField(max_length=100)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED')], max_length=100)),
                ('depatmemnt', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('funding_agency', models.CharField(max_length=100)),
                ('grand_sanctioned', models.IntegerField()),
                ('grand_recived', models.IntegerField()),
                ('publictaion_details', models.FileField(upload_to='research/FundedProjects')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='batch',
        ),
    ]
