# Generated by Django 3.2.13 on 2023-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20230108_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fundedprojects',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
