# Generated by Django 3.2.13 on 2023-01-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_auto_20230108_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundedprojects',
            old_name='depatmemnt',
            new_name='department',
        ),
    ]
