# Generated by Django 3.2.13 on 2023-01-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_rename_depatmemnt_fundedprojects_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicconsultancy',
            old_name='work_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='academicconsultancy',
            name='publictaion_details',
        ),
    ]
