# Generated by Django 3.2.13 on 2023-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20230114_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile',
            field=models.FileField(default='faculty_profile.pdf', upload_to='faculty_profile'),
        ),
    ]
