# Generated by Django 3.2.13 on 2023-01-31 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_faculty_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
