# Generated by Django 3.2.13 on 2023-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_auto_20230131_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event_type',
            field=models.ManyToManyField(default='None', to='website.GalleryEventTypes'),
        ),
    ]
