# Generated by Django 3.2.13 on 2023-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVissionANDMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=250)),
                ('name', models.CharField(choices=[('Vision', 'Vision'), ('Mission', 'Mission'), ('objectives', 'objectives')], max_length=10)),
            ],
            options={
                'verbose_name': 'Placement Vission and Mission',
                'verbose_name_plural': 'Placement Vissions and Missions',
            },
        ),
    ]
