# Generated by Django 3.2.17 on 2023-04-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_placementfaculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacementFaculty',
        ),
    ]
