# Generated by Django 3.2.17 on 2023-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0009_placementgallery_placementstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementfaculty',
            name='role',
            field=models.CharField(max_length=40),
        ),
    ]
