# Generated by Django 3.2.17 on 2023-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0010_alter_placementfaculty_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementfaculty',
            name='role',
            field=models.CharField(max_length=70),
        ),
    ]
