# Generated by Django 3.2.17 on 2023-09-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0012_placementstatstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementstatstable',
            name='avg',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='placementstatstable',
            name='highest',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='placementstatstable',
            name='year',
            field=models.CharField(choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='None', max_length=30),
        ),
    ]
