# Generated by Django 3.2.17 on 2023-12-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0013_auto_20230929_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('year', models.CharField(choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='None', max_length=30)),
            ],
        ),
    ]
