# Generated by Django 3.2.17 on 2023-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0014_placementlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementstatstable',
            name='avg',
        ),
        migrations.AddField(
            model_name='placementstatstable',
            name='entrepreneurship',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementstatstable',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
