# Generated by Django 3.2.23 on 2023-12-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0015_auto_20231207_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Batchstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default=None, max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('placements', models.CharField(max_length=100)),
                ('higher_studies', models.CharField(max_length=100)),
                ('entrepreneurship', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('table', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='placements.tables')),
            ],
        ),
    ]
