# Generated by Django 3.2.23 on 2023-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0016_batchstat_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchstat',
            name='table',
        ),
        migrations.AddField(
            model_name='tables',
            name='data',
            field=models.ManyToManyField(blank=True, to='placements.Batchstat'),
        ),
    ]
