# Generated by Django 3.2.23 on 2024-03-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0017_auto_20231209_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementlist',
            name='year',
            field=models.CharField(choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='placementstatstable',
            name='year',
            field=models.CharField(choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='None', max_length=30),
        ),
    ]
