# Generated by Django 3.2.25 on 2025-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0018_auto_20250219_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstat',
            name='Dep',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('None', 'None')], default=None, max_length=100),
        ),
    ]
