# Generated by Django 3.2.25 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0021_alter_batchstat_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstat',
            name='Dep',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default=None, max_length=100),
        ),
    ]
