# Generated by Django 3.2.13 on 2022-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='img',
            field=models.ImageField(default='img.png', upload_to='Management'),
        ),
    ]
