# Generated by Django 3.2.13 on 2022-12-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0002_management_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cceinmedia',
            options={'verbose_name_plural': 'CCE in Media'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name_plural': 'Management'},
        ),
        migrations.AlterModelOptions(
            name='moreaboutcce',
            options={'verbose_name_plural': 'More About CCE'},
        ),
    ]
