# Generated by Django 3.2.13 on 2023-01-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0003_auto_20221208_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
