# Generated by Django 3.2.17 on 2023-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0005_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditedStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='AuditedStatements')),
            ],
            options={
                'verbose_name_plural': 'Audited Statements',
            },
        ),
    ]
