# Generated by Django 3.2.17 on 2023-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0006_auditedstatements'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='CollegeCalendar')),
            ],
            options={
                'verbose_name_plural': 'College Calendar',
            },
        ),
    ]
