# Generated by Django 3.2.17 on 2023-05-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0008_collegemagazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AicteApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='AicteApprovals')),
            ],
            options={
                'verbose_name_plural': 'AICTE Approvals',
            },
        ),
        migrations.CreateModel(
            name='KtuRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='KtuRegulations')),
            ],
            options={
                'verbose_name_plural': 'KTU Regulations',
            },
        ),
        migrations.CreateModel(
            name='MandatoryDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='MandatoryDisclosure')),
            ],
            options={
                'verbose_name_plural': 'Mandatory Disclosure',
            },
        ),
    ]
