# Generated by Django 3.2.17 on 2023-11-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0010_resultanalysis_resulttable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegemagazine',
            options={'verbose_name': 'Magazine / Newsletter', 'verbose_name_plural': 'Magazines / Newsletters'},
        ),
        migrations.RemoveField(
            model_name='collegemagazine',
            name='name',
        ),
        migrations.AddField(
            model_name='collegemagazine',
            name='image',
            field=models.ImageField(default='None', upload_to='CollegeMagazineImages'),
        ),
        migrations.AddField(
            model_name='collegemagazine',
            name='title',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
