# Generated by Django 4.2.7 on 2023-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0010_resultanalysis_resulttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='KtuAffiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='KtuAffiliations')),
            ],
            options={
                'verbose_name_plural': 'KTU Affiliations',
            },
        ),
    ]
