# Generated by Django 3.2.23 on 2023-11-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0014_auto_20231129_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='AcademicCalendar')),
            ],
            options={
                'verbose_name_plural': 'Academic Calendar',
            },
        ),
        migrations.DeleteModel(
            name='CollegeCalendar',
        ),
    ]
