# Generated by Django 3.2.25 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0018_alter_committee_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default=('2025-2026', '2025-2026'), max_length=200),
        ),
    ]
