# Generated by Django 3.2.13 on 2022-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_associations_professionalbodies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.IntegerField(max_length=10)),
                ('course_credits', models.IntegerField(max_length=10)),
                ('course_information_sheet', models.FileField(upload_to='Handouts/InformationSheets')),
                ('course_notes', models.FileField(upload_to='Handouts/Notes')),
                ('semester', models.CharField(choices=[('S1&S2', 'S1&S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8')], default='S1&S2', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusPDFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='SyllabusPDFS')),
            ],
        ),
    ]
