# Generated by Django 3.2.13 on 2022-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_handouts_syllabuspdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='handouts',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='handouts',
            name='course_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='handouts',
            name='course_credits',
            field=models.IntegerField(),
        ),
    ]
