# Generated by Django 3.2.13 on 2022-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_auto_20221206_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuspdfs',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200),
        ),
    ]
