# Generated by Django 3.2.13 on 2022-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_syllabuspdfs_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='LaboratoriesImages')),
                ('data', models.CharField(max_length=500)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('faculties', models.ManyToManyField(blank=True, to='website.Faculty')),
            ],
            options={
                'verbose_name': 'Labs',
                'verbose_name_plural': 'Laboratories',
            },
        ),
    ]
