# Generated by Django 3.2.13 on 2022-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_alter_depabout_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depabout',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('faculty', 'Faculties'), ('associations', 'Associations'), ('professionalBodies', 'Professional Bodies'), ('curriculum_and_syllabus', 'Sylabus')], default='About', max_length=200),
        ),
    ]
