# Generated by Django 3.2.13 on 2022-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_alter_depabout_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('workshops_seminars', 'Workshops / Seminars'), ('addons', 'Add-Ons'), ('iv', 'Industrial Visits')], default='iv', max_length=100),
        ),
    ]
