# Generated by Django 3.2.13 on 2022-12-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_events_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(default='None', upload_to='EventsImages'),
        ),
    ]
