# Generated by Django 3.2.13 on 2023-01-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_auto_20221212_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='NewsLetters')),
            ],
            options={
                'verbose_name': 'NewsLetters',
                'verbose_name_plural': 'NewsLetterss',
            },
        ),
    ]
