# Generated by Django 3.2.13 on 2023-01-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='image',
            field=models.ImageField(default='None', upload_to='NewsLettersImages'),
        ),
    ]
