# Generated by Django 3.2.13 on 2023-01-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_auto_20230104_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationsevents',
            name='department',
        ),
        migrations.RemoveField(
            model_name='associationteammembers',
            name='department',
        ),
    ]
