# Generated by Django 3.2.13 on 2023-01-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_auto_20230104_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalbodies',
            name='image',
            field=models.ImageField(default='None', upload_to='ProfessionalBodiesImages'),
        ),
        migrations.CreateModel(
            name='ProfessionalBodiesTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ProfessionalBodies')),
                ('ProfessionalBodies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.professionalbodies')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBodiesEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('short_description', models.CharField(default='None', max_length=500)),
                ('image', models.ImageField(upload_to='ProfessionalBodiesImagesEvents')),
                ('ProfessionalBodies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.professionalbodies')),
            ],
        ),
    ]
