# Generated by Django 3.2.13 on 2023-01-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0021_auto_20230104_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalbodies',
            name='hero_image',
            field=models.ImageField(default='None', upload_to='ProfessionalBodiesImages/Hero_images'),
        ),
    ]
