# Generated by Django 3.2.13 on 2023-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_professionalbodies_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associations',
            name='link',
        ),
        migrations.RemoveField(
            model_name='professionalbodies',
            name='link',
        ),
        migrations.AddField(
            model_name='associations',
            name='hero_image',
            field=models.ImageField(default='None', upload_to='AssociationsImages/Hero_images'),
        ),
    ]
