# Generated by Django 3.2.13 on 2023-01-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0023_auto_20230104_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('data', models.CharField(max_length=500)),
            ],
        ),
    ]
