# Generated by Django 3.2.13 on 2023-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0024_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationteammembers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
