# Generated by Django 3.2.13 on 2023-02-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0026_professionalbodiesteammembers_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalbodiesteammembers',
            name='priority',
        ),
    ]
