# Generated by Django 3.2.17 on 2023-05-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0029_alter_achivements_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=200),
        ),
    ]
