# Generated by Django 3.2.17 on 2023-05-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0033_innovativetlm_tlm_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlm_table',
            name='title',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.innovativetlm'), max_length=200),
        ),
    ]
