# Generated by Django 3.2.17 on 2023-05-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0037_streamcomm_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=('2022-2023', '2022-2023'), max_length=200),
        ),
    ]
