# Generated by Django 3.2.17 on 2023-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0039_alter_events_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalbodiesteammembers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
