# Generated by Django 3.2.17 on 2023-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0041_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handouts',
            name='course_information_sheet',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='handouts',
            name='course_notes',
            field=models.URLField(),
        ),
    ]
