# Generated by Django 3.2.17 on 2023-09-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0042_auto_20230922_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handouts',
            name='course_code',
            field=models.CharField(max_length=30),
        ),
    ]
