# Generated by Django 3.2.17 on 2023-09-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0043_alter_handouts_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('organizer', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
            ],
        ),
    ]
