# Generated by Django 3.2.17 on 2023-09-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0044_achievementtables'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementtables',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=200),
        ),
        migrations.AddField(
            model_name='achievementtables',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=('2022-2023', '2022-2023'), max_length=200),
        ),
    ]
