# Generated by Django 3.2.17 on 2023-09-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0045_auto_20230926_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtables',
            name='date',
        ),
    ]
