# Generated by Django 3.2.17 on 2023-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0046_remove_achievementtables_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depabout',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('faculty', 'Faculties'), ('associations', 'Associations'), ('professionalBodies', 'Professional Bodies'), ('curriculum_and_syllabus', 'Sylabus'), ('labs', 'labs')], default='About', max_length=200),
        ),
    ]
