# Generated by Django 3.2.17 on 2023-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0048_fdps_mooc_courses_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Higher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=('2022-2023', '2022-2023'), max_length=200)),
                ('students_pdf', models.FileField(upload_to='')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Holistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='EventsImages')),
                ('poster', models.ImageField(default='None', upload_to='EventsImages')),
                ('data', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='None', max_length=200)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('type', models.CharField(choices=[('workshops_seminars', 'Workshops / Seminars'), ('addons', 'Add-Ons'), ('iv', 'Industrial Visits')], default='iv', max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Holistic',
                'verbose_name_plural': 'Holistics',
            },
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=('2022-2023', '2022-2023'), max_length=200)),
                ('students_pdf', models.FileField(upload_to='')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Social_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Social_activitiesImages')),
                ('poster', models.ImageField(default='None', upload_to='EventsImages')),
                ('data', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='None', max_length=200)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('type', models.CharField(choices=[('workshops_seminars', 'Workshops / Seminars'), ('addons', 'Add-Ons'), ('iv', 'Industrial Visits')], default='iv', max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Activity',
                'verbose_name_plural': 'Social Activities',
            },
        ),
    ]
