# Generated by Django 3.2.17 on 2023-11-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0051_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_pdfs',
            field=models.FileField(default='None', upload_to='pdfs/activity'),
        ),
    ]
