# Generated by Django 4.2.7 on 2023-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0054_auto_20231108_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements',
            name='data',
            field=models.TextField(),
        ),
    ]
