# Generated by Django 3.2.17 on 2023-11-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0054_auto_20231108_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('workshops_seminars', 'Workshops / Seminars'), ('addons', 'Add-Ons'), ('iv', 'Industrial Visits'), ('competitions', 'competetions')], default='iv', max_length=100),
        ),
    ]
