# Generated by Django 3.2.17 on 2023-11-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0055_alter_events_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
            ],
            options={
                'verbose_name': 'Research About',
                'verbose_name_plural': 'Research Abouts',
            },
        ),
    ]
