# Generated by Django 3.2.17 on 2023-11-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0056_researchabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ExtraEventsImages')),
                ('poster', models.ImageField(default='None', upload_to='ExtraEventsImages')),
                ('data', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='None', max_length=200)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('None', 'None')], default='None', max_length=200)),
                ('type', models.CharField(choices=[('sports', 'Sports'), ('arts', 'Arts')], default='sports', max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Extra Curricular Event',
                'verbose_name_plural': 'Extra Curricular Events',
            },
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Co Curricular Event', 'verbose_name_plural': 'Co Curricular Events'},
        ),
    ]
