# Generated by Django 3.2.17 on 2023-11-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0060_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements',
            name='data',
            field=models.TextField(),
        ),
    ]
