# Generated by Django 3.2.17 on 2023-11-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0061_alter_achivements_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlm_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='tlm_table_data'),
        ),
        migrations.AddField(
            model_name='tlm_table',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
