# Generated by Django 3.2.17 on 2023-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0063_facultypdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('workshops_seminars', 'Workshops / Seminars'), ('Value', 'Value Added Courses'), ('iv', 'Industrial Visits'), ('competitions', 'competetions')], default='iv', max_length=100),
        ),
    ]
