# Generated by Django 3.2.17 on 2023-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0065_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placements',
            name='year',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
