# Generated by Django 3.2.23 on 2024-03-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0066_alter_placements_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtables',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default=('2023-2024', '2023-2024'), max_length=200),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default=('2023-2024', '2023-2024'), max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='extraevents',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultypdf',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default=('2023-2024', '2023-2024'), max_length=200),
        ),
        migrations.AlterField(
            model_name='higher',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default=('2023-2024', '2023-2024'), max_length=200),
        ),
        migrations.AlterField(
            model_name='holistics',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='mooc_courses',
            name='year',
            field=models.TextField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=30),
        ),
        migrations.AlterField(
            model_name='social_activities',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], default=('2023-2024', '2023-2024'), max_length=200),
        ),
    ]
