# Generated by Django 3.2.25 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0068_auto_20250616_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('None', 'None')], default='None', max_length=200)),
                ('btech_s1_syllabus', models.FileField(blank=True, upload_to='Autonomous/BTech', verbose_name='B.Tech S1 Syllabus')),
                ('btech_s2_syllabus', models.FileField(blank=True, upload_to='Autonomous/BTech', verbose_name='B.Tech S2 Syllabus')),
                ('mtech_s1_syllabus', models.FileField(blank=True, upload_to='Autonomous/MTech', verbose_name='M.Tech S1 Syllabus')),
                ('mtech_s2_syllabus', models.FileField(blank=True, upload_to='Autonomous/MTech', verbose_name='M.Tech S2 Syllabus')),
            ],
            options={
                'verbose_name': 'Autonomous Curriculum',
                'verbose_name_plural': 'Autonomous Curriculums',
            },
        ),
        migrations.AlterField(
            model_name='achievementtables',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default=('2025-2026', '2025-2026'), max_length=200),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default=('2025-2026', '2025-2026'), max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='extraevents',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultypdf',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default=('2025-2026', '2025-2026'), max_length=200),
        ),
        migrations.AlterField(
            model_name='higher',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default=('2025-2026', '2025-2026'), max_length=200),
        ),
        migrations.AlterField(
            model_name='holistics',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='mooc_courses',
            name='year',
            field=models.TextField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=30),
        ),
        migrations.AlterField(
            model_name='social_activities',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default=('2025-2026', '2025-2026'), max_length=200),
        ),
    ]
