# Generated by Django 3.2.25 on 2026-01-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0069_auto_20260121_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtables',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='dep',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='associations',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='autonomouscurriculum',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='dab',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='dabtable',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='depabout',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='dephero',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='depupdates',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='econtent',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='extraevents',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultypdf',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='fdps',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='handouts',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='higher',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='holistics',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='innovativetlm',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='mooc_courses',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='pac',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='pactable',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='placements',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='poes',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='pos',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='professionalbodies',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='psos',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='researchabout',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='social_activities',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='streams',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabuspdfs',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='vission',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200),
        ),
    ]
