# Generated by Django 3.2.25 on 2026-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0072_add_ds_bs_syllabus_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200)),
                ('data', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'WK',
            },
        ),
        migrations.AddField(
            model_name='autonomouscurriculum',
            name='btech_ec_s1_syllabus',
            field=models.FileField(blank=True, upload_to='Autonomous/BTech_EC', verbose_name='B.Tech EC S1 Syllabus'),
        ),
        migrations.AddField(
            model_name='autonomouscurriculum',
            name='btech_ec_s2_syllabus',
            field=models.FileField(blank=True, upload_to='Autonomous/BTech_EC', verbose_name='B.Tech EC S2 Syllabus'),
        ),
        migrations.AddField(
            model_name='autonomouscurriculum',
            name='btech_vlsi_s1_syllabus',
            field=models.FileField(blank=True, upload_to='Autonomous/BTech_VLSI', verbose_name='B.Tech VLSI S1 Syllabus'),
        ),
        migrations.AddField(
            model_name='autonomouscurriculum',
            name='btech_vlsi_s2_syllabus',
            field=models.FileField(blank=True, upload_to='Autonomous/BTech_VLSI', verbose_name='B.Tech VLSI S2 Syllabus'),
        ),
    ]
