# Generated by Django 3.2.25 on 2026-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0073_auto_20260916_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('BSH', 'BSH'), ('DS', 'DS'), ('BS', 'BS'), ('MBA', 'MBA'), ('None', 'None')], default='None', max_length=200)),
                ('syllabus_type', models.CharField(choices=[('ktu', 'KTU Syllabus'), ('autonomous', 'Autonomous Syllabus')], default='ktu', help_text='Whether this is a KTU-affiliated or Autonomous syllabus', max_length=20)),
                ('program', models.CharField(blank=True, default='', help_text='e.g. B.Tech (CSE), B.Tech (Data Science), M.Tech, MBA, MCA, B.Tech (EC), B.Tech (VLSI), etc.', max_length=200)),
                ('semester', models.CharField(blank=True, default='', help_text='e.g. S1, S2, S3, S4, S5, S6, S7, S8, S1&S2', max_length=50)),
                ('title', models.CharField(help_text='Display title for the document', max_length=300)),
                ('file', models.FileField(upload_to='CurriculumDocuments')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Curriculum & Syllabus Document',
                'verbose_name_plural': 'Curriculum & Syllabus Documents',
                'ordering': ['department', 'syllabus_type', 'program', 'order', 'semester'],
            },
        ),
        migrations.AlterModelOptions(
            name='autonomouscurriculum',
            options={'verbose_name': 'Autonomous Curriculum (Legacy)', 'verbose_name_plural': 'Autonomous Curriculums (Legacy)'},
        ),
    ]
