# Generated by Django 3.2.17 on 2023-04-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_hero_image_page'),
        ('studentservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=250)),
                ('name', models.CharField(choices=[('Vision', 'Vision'), ('Mission', 'Mission')], max_length=10)),
            ],
            options={
                'verbose_name': 'Central Library',
                'verbose_name_plural': 'Central Library',
            },
        ),
        migrations.CreateModel(
            name='DigitalLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='CentralLibrary/DigitalLibrary/')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
            ],
        ),
    ]
