# Generated by Django 3.2.17 on 2023-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0002_centrallibrary_digitallibrary_libraryfaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrallibrary',
            name='name',
            field=models.CharField(choices=[('Vision', 'Vision'), ('Mission', 'Mission'), ('about', 'about')], max_length=10),
        ),
    ]
