# Generated by Django 3.2.13 on 2023-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentServices', '0002_auto_20230103_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsteamstatus',
            name='logo',
            field=models.ImageField(default='arts/teams/logos/default.png', upload_to='arts/teams/logos'),
        ),
    ]
