# Generated by Django 3.2.13 on 2023-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentServices', '0003_artsteamstatus_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arts/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SportsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='sports/events')),
            ],
        ),
        migrations.CreateModel(
            name='SportsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arts/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SportsTeamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(choices=[('cetus', 'cetus'), ('pegasus', 'pegasus'), ('taurs', 'taurs'), ('lupus', 'lupus')], max_length=100)),
                ('logo', models.ImageField(default='sports/teams/logos/default.png', upload_to='sports/teams/logos')),
                ('score', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('color', models.CharField(default='red-700', max_length=100)),
                ('image', models.ImageField(upload_to='sports/teams')),
            ],
        ),
        migrations.CreateModel(
            name='SportsUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.TextField(default='No data')),
                ('date', models.DateField()),
            ],
        ),
    ]
