# Generated by Django 3.2.13 on 2023-01-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20230104_0620'),
        ('StudentServices', '0004_artsgallery_sportsevents_sportsgallery_sportsteamstatus_sportsupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='NssEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='nss/events')),
            ],
        ),
        migrations.CreateModel(
            name='NssGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nss/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='NssStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='nss/students')),
            ],
        ),
        migrations.CreateModel(
            name='NssFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ManyToManyField(to='website.Faculty')),
            ],
        ),
    ]
