# Generated by Django 3.2.17 on 2023-09-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0005_auto_20230616_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('image', models.ImageField(upload_to='nss/students')),
            ],
        ),
        migrations.RemoveField(
            model_name='nssfaculty',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='NssStudents',
        ),
        migrations.DeleteModel(
            name='NssFaculty',
        ),
    ]
