# Generated by Django 3.2.13 on 2023-02-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentServices', '0006_clubs_iiccertificate_iiccommitee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iiccommitee',
            old_name='phone',
            new_name='member_type',
        ),
    ]
