# Generated by Django 3.2.17 on 2023-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0007_mentoring_mentoringevents_mentoringteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEEEJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
