# Generated by Django 3.2.13 on 2023-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentServices', '0007_rename_phone_iiccommitee_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iiccertificate',
            name='image',
            field=models.FileField(upload_to='iic/certificates'),
        ),
    ]
