# Generated by Django 3.2.13 on 2023-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentServices', '0008_alter_iiccertificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenCellCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('designamtion', models.CharField(max_length=300)),
            ],
        ),
    ]
