# Generated by Django 3.2.13 on 2023-02-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentServices', '0009_womencellcommitee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnionCommitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='union/member', verbose_name='Member Image')),
                ('position', models.CharField(max_length=300)),
            ],
        ),
    ]
