# Generated by Django 3.2.17 on 2023-09-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0009_ircabout_ircevents_ircteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='data',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='centrallibrary',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='link',
            field=models.CharField(default='default.com', max_length=100),
        ),
        migrations.CreateModel(
            name='ClubMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('image', models.ImageField(upload_to='nss/students')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentservices.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='ClubEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='clubs/events')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentservices.clubs')),
            ],
        ),
    ]
