# Generated by Django 3.2.17 on 2023-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0011_ieeeabout_ieeeevents_ieeemembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCILAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CCILEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='CCIL/events')),
            ],
        ),
        migrations.CreateModel(
            name='CCILTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('image', models.ImageField(upload_to='CCIL/members')),
            ],
        ),
    ]
