# Generated by Django 3.2.17 on 2023-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0013_alter_libraryfaculty_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Library Info',
                'verbose_name_plural': "Library Infos'",
            },
        ),
    ]
