# Generated by Django 3.2.17 on 2023-11-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0014_libraryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubsHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Clubs_Heros_Images')),
                ('video', models.FileField(blank=True, upload_to='Clubs_Heros_Videos')),
                ('type', models.CharField(choices=[('img', 'IMAGE'), ('vdo', 'VIDEO')], default='img', max_length=200)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentservices.clubs')),
            ],
            options={
                'verbose_name_plural': 'Clubs Hero Images',
            },
        ),
    ]
