# Generated by Django 3.2.17 on 2023-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0017_ccevrabout_ccevrevents_ccevrteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='union/Central_library', verbose_name='central_library Image')),
            ],
        ),
    ]
