# Generated by Django 3.2.17 on 2023-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0019_womenevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCILGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cciol/gallery')),
            ],
        ),
    ]
