# Generated by Django 3.2.25 on 2026-10-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0020_ccilgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeInCCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='make_in_cce/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Make In CCE Item',
                'verbose_name_plural': 'Make In CCE Items',
            },
        ),
    ]
